### ISSUE TITLE
Time not synched in windows

### ISSUE THREAD

**Issue by rajagopalx** [naanal/dgp#12]
Initial Step Taken:

Using salt, I changed time

`salt '*' cmd.run 'time 10:00:00 AM'`

**Comment by shanmuganathans** [comment]
solution1:
set correct time in server

`Net time \\servername /Set /y `

Run above cmd on all workstations

solution2:
windows Active Directory 2012

`Net time \\servername /Set /y ` save the cmd as .ps1 file

Edit Group Policy -->user configuration -->windows settings -->scripts -->logon
Select the powershell file(.ps1) 
click ok

Note: For apply this change Need to restart the Instances

**Comment by shanmuganathans** [comment]
Windows PowerShell to force a time resynchronization. 
`W32tm /resync /force`

**Comment by rajagopalx** [comment]
I uploaded sample ansible playbooks on management node. Modify it for your requirements.

**Comment by rajagopalx** [comment]
Currently We have below scenarios,

1.  Time of windows server is not synched.
2.  Time of windows desktop connected to AD is not synched.
3.  Time of standalone windows desktop is not synched. 

On Scenario 1 and 3, time is changed on reboot
On Scenario 2, Time must automatically sync from AD server but sometimes time might not get synched. For this scenario shan's work is much useful

Possible Solution:

Basically We need to install ntp server on our ubuntu host and point this ntp to windows server and standalone desktops

**How to set up ntp server for windows server?**

```
w32tm /config /manualpeerlist:<host-ip> /syncfromflags:manual /reliable:yes /update
net stop w32time
net start w32time
```

[https://serverfault.com/questions/182834/windows-server-2008-r2-no-internet-time-tab](url)


**How to set up ntp server for desktop ?**

By default, time server is disabled on desktop
Enable it  `sc config W32Time start= auto`
run the above commands.

Gui:
[https://superuser.com/questions/954477/where-do-i-find-the-internet-time-ntp-settings-in-windows-10](url)

I personally checked this and it's working
